#!/bin/bash

bluetoothctl disconnect
pactl unload-module module-bluetooth-discover
pactl load-module module-bluetooth-discover
if bluetoothctl connect 88:C9:E8:52:BA:0C; then
  sleep 3s
  # Don't need this with ergodox
  setxkbmap -option caps:escape
  # xmodmap ~/.Xmodmap
  chime && chime
fi
