#!/bin/bash

source $GBASH_ROOT/gbash.sh || exit 1

DEFINE_string t "Release" "Which output directory to use"
gbash::init_google "$@"

if autoninja -C ~/chrome/src/out/${FLAGS_t}; then
  chime
  rchrome -t=${FLAGS_t} ${GBASH_ARGV[@]}
else
  sadchime
fi
