#!/bin/bash
WINDOW_GEOMETRY=$(xdotool getactivewindow | xargs xdotool getwindowgeometry)
NUMBERS=($(echo ${WINDOW_GEOMETRY} | grep -oP "\d+"))

# emojikeyboard window is 250x46
X=$(expr ${NUMBERS[1]} + ${NUMBERS[4]} / 2 - 250 / 2)
Y=$(expr ${NUMBERS[2]} + 200)
emoji-keyboard -s
wmctrl -r "Search emoji" -e 0,$X,$Y,-1,-1
wmctrl -R "Search emoji"
