#!/bin/bash
# PREVIOUS_WINDOW_ID=$(cat $HOME/bin/previous-window-id)
# ACTIVE_WINDOW_NAME=$(xdotool getactivewindow | xargs xdotool getwindowname)

# if echo $ACTIVE_WINDOW_NAME | grep Terminal; then
# xdotool windowactivate $PREVIOUS_WINDOW_ID
# else
# PREVIOUS_WINDOW_ID=$(xdotool getactivewindow)
# echo $PREVIOUS_WINDOW_ID > $HOME/bin/previous-window-id
# TERMINAL_WINDOWS=$(xdotool search --onlyvisible --class terminal)
# for WINDOW_NUM in $TERMINAL_WINDOWS; do
#   xdotool windowactivate $WINDOW_NUM
# done
# fi

TERMINAL_WINDOWS=$(xdotool search --onlyvisible --class terminal)
for WINDOW_NUM in $TERMINAL_WINDOWS; do
  xdotool windowactivate $WINDOW_NUM
done