#!/bin/bash

source $GBASH_ROOT/gbash.sh || exit 1

DEFINE_string d "Release" "Which output directory to use"
DEFINE_string profile "0" "Profile directory to use"
DEFINE_array vm --type=string --delim=, "" "Extra vmodules"
gbash::init_google "$@"

cd $HOME/chrome/src

TARGET_DIR=${FLAGS_d}

VMODULES=(
)

VMODULES_STRING=""
for i in ${FLAGS_vm[@]}; do
  VMODULES_STRING="${VMODULES_STRING}$i=3,"
done
for i in ${VMODULES[@]}; do
  VMODULES_STRING="${VMODULES_STRING}$i=3,"
done

COMMON_ANCESTOR=$(git merge-base HEAD origin/main)
function auto_vmodules() {
  for l in `git diff --name-only $COMMON_ANCESTOR | egrep "\.(cc|h)$"`; do
    echo `basename ${l%.*}`
  done | sort -u
}
for i in `auto_vmodules`; do
  VMODULES_STRING="${VMODULES_STRING}$i=3,"
done


function ene() {
  echo "$@";
  exec "$@";
}

  # --disable-gpu-vsync \
  # --force-color-profile=srgb \
  # --force-device-scale-factor=0.5 \
  # --ensure-forced-color-profile \
  # --enable-blink-features=CanvasColorManagement \
  # --force-gpu-rasterization \
  # --force-high-contrast \
  # --disable-accelerated-2d-canvas \
  # --use-gl=angle --use-angle=gl --use-cmd-decoder=passthrough \
  # --disable-gpu-compositing \
  # --new-canvas-2d-api \
  # --enable-blink-features=CSSColorTypedOM \
  # --enable-features=Vulkan,VulkanFromANGLE \
  # --disable-features=Canvas2dStaysGPUOnReadback \
  # --use-gl=eglgl \
  # --user-data-dir=../profiles/${FLAGS_profile}/ \
  # --enable-gpu-rasterization \
  # --use-vulkan=swiftshader \
  # --disable-vulkan-fallback-to-gl-for-testing \
  # --use-gl=swiftshader \
  # --use-angle=swiftshader \
  # --single-process \

ene out/${TARGET_DIR}/chrome \
  --enable-experimental-web-platform-features \
  --enable-logging=stderr \
  --enable-precise-memory-info \
  --js-flags="--expose-gc" \
  --vmodule="${VMODULES_STRING}" \
  --user-data-dir=../profiles/0/ \
  ${GBASH_ARGV[@]}
