#!/bin/bash

source $GBASH_ROOT/gbash.sh || exit 1

DEFINE_string t "Release" "Which output directory to use"
DEFINE_string profile "0" "Profile directory to use"
DEFINE_array vm --type=string --delim=, "" "Extra vmodules"
gbash::init_google "$@"

cd $HOME/chrome/src

TARGET_DIR=${FLAGS_t}

VMODULES=(
)

VMODULES_STRING=""
for i in ${FLAGS_vm[@]}; do
  VMODULES_STRING="${VMODULES_STRING}$i=3,"
done
for i in ${VMODULES[@]}; do
  VMODULES_STRING="${VMODULES_STRING}$i=3,"
done

COMMON_ANCESTOR=$(git merge-base HEAD origin/master)
function auto_vmodules() {
  for l in `git diff --name-only $COMMON_ANCESTOR | egrep "\.(cc|h)$"`; do
    echo `basename ${l%.*}`
  done | sort -u
}
for i in `auto_vmodules`; do
  VMODULES_STRING="${VMODULES_STRING}$i=3,"
done


function ene() {
  echo "$@";
  exec "$@";
}

  # --disable-gpu-vsync \
  # --force-color-profile=srgb \
  # --force-device-scale-factor=0.5 \
  # --ensure-forced-color-profile \
  # --use-gl=angle --use-angle=gl --use-cmd-decoder=passthrough \
  # --enable-accelerated-2d-canvas \
  # --enable-experimental-web-platform-features \
  # --disable-accelerated-2d-canvas \
  # --use-gl=swiftshader \

ene out/${TARGET_DIR}/chrome \
  --enable-logging=stderr \
  --user-data-dir=../profiles/${FLAGS_profile}/ \
  --force-gpu-rasterization \
  --enable-experimental-canvas-features \
  --enable-precise-memory-info \
  --js-flags="--expose-gc" \
  --vmodule="${VMODULES_STRING}" \
  ${GBASH_ARGV[@]}