#!/bin/bash

cd ~/chrome/src
if git rebase-update; then
  if gclient sync --jobs=256; then
    if autoninja -C ~/chrome/src/out/Release
      chime
    else
      sadchime
  else
    sadchime
  fi
else
  sadchime
fi
