#!/bin/bash

cd ~/chrome/src
if  gcert && git rebase-update -n && git rebase-update && \
    gclient sync -D --jobs=256 && \
    autoninja -C ~/chrome/src/out/Release && \
    tools/clang/scripts/generate_compdb.py -p out/Release > compile_commands.json
then
  chime
else
  sadchime
fi
