#!/bin/bash

cd ~/chrome/src
if git rebase-update; then
  if gclient sync -D --jobs=256; then
    if autoninja -C ~/chrome/src/out/Release; then
      chime
    else
      sadchime
    fi
  else
    sadchime
  fi
else
  sadchime
fi
